services:
  configsvr1:
    image: mongo
    container_name: cfg
    restart: always
    command: mongod --configsvr --replSet configReplSet --bind_ip localhost --port 27016
    volumes:
      - /home/algiz/volumes/mongo-cfg-server:/data/db
    ports:
      - "27016:27016"
    networks:
      - mongo-cluster

  mongos:
    image: mongo
    container_name: server
    restart: always
    command: mongos --configdb configReplSet/configsvr1:27016 --bind_ip localhost --port 27010
#    volumes:
#      - /home/algiz/volumes/mongo-server:/data/db
    ports:
      - "27010:27010"
    depends_on:
      - configsvr1
    networks:
      - mongo-cluster

  shard1svr1:
    image: mongo
    container_name: sh1r1
    restart: always
#    volumes:
#      - /home/algiz/volumes/mongo-shard1svr1:/data/db
    command: mongod --shardsvr --replSet shard1 --bind_ip localhost --port 27018
    ports:
      - "27018:27018"
    networks:
      - mongo-cluster

  shard1svr2:
    image: mongo
    container_name: sh1r2
    restart: always
#    volumes:
#      - /home/algiz/volumes/mongo-shard1svr2:/data/db
    command: mongod --shardsvr --replSet shard1 --bind_ip localhost --port 27019
    ports:
      - "27019:27019"
    networks:
      - mongo-cluster

  shard2svr1:
    image: mongo
    container_name: sh2r1
    restart: always
#    volumes:
#      - /home/algiz/volumes/mongo-shard2svr1:/data/db
    command: mongod --shardsvr --replSet shard2 --bind_ip localhost --port 27021
    ports:
      - "27021:27021"
    networks:
      - mongo-cluster

  shard2svr2:
    image: mongo
    container_name: sh2r2
    restart: always
#    volumes:
#      - /home/algiz/volumes/mongo-shard2svr2:/data/db
    command: mongod --shardsvr --replSet shard2 --bind_ip localhost --port 27021
    ports:
      - "27022:27022"
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge