services:
  configsvr1:
    image: mongo
    container_name: cfg1
    restart: always
    command: mongod --configsvr --replSet cfg --bind_ip_all --port 27015
#    volumes:
#      - /home/algiz/volumes/mongo-cfg-server1:/data/db
    ports:
      - "27015:27015"
    depends_on:
      - shard1
      - shard2
    networks:
      - mongo-cluster

  mongos:
    image: mongo
    container_name: server
    restart: always
    command: mongos --configdb cfg/configsvr1:27015 --bind_ip_all --port 27010
#    volumes:
#      - /home/algiz/volumes/mongo-server:/data/db
    ports:
      - "27010:27010"
    depends_on:
      - configsvr1
    networks:
      - mongo-cluster

  shard1:
    image: mongo
    container_name: sh1
    restart: always
#    volumes:
#      - /home/algiz/volumes/mongo-shard1:/data/db
    command: mongod --shardsvr --replSet shard1 --bind_ip_all --port 27018
    ports:
      - "27018:27018"
    networks:
      - mongo-cluster

  shard2:
    image: mongo
    container_name: sh2
    restart: always
#    volumes:
#      - /home/algiz/volumes/mongo-shard2:/data/db
    command: mongod --shardsvr --replSet shard2 --bind_ip_all --port 27019
    ports:
      - "27019:27019"
    networks:
      - mongo-cluster
networks:
  mongo-cluster:
    driver: bridge