services:
  server:
    image: mongo
    container_name: server
    restart: always
    volumes:
      - /home/algiz/volumes/mongo-server:/data/db
    ports:
      - 27001:27017
    networks:
      - mongo
    entrypoint: [ "/usr/bin/mongos", "--bind_ip_all", "--configdb", "dz-2_mongo/config:27017" ]
    depends_on:
      - config
      - shard1
      - shard2

  config:
    image: mongo
    container_name: config
    restart: always
    volumes:
      - /home/algiz/volumes/mongo-config:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--configsvr", "--replSet", "cfg", "--port", "27017" ]
#    links:
#      - shard1
#      - shard2

  shard1:
    image: mongo
    container_name: shard1
    restart: always
    volumes:
      - /home/algiz/volumes/mongo-shard1:/data/db
    ports:
      - 27010:27017
    networks:
      - mongo
    entrypoint: [ "/usr/bin/mongod", "--shardsvr", "--bind_ip_all", "--replSet", "shard1" ]
  shard12:
    image: mongo
    container_name: shard12
    restart: always
    volumes:
      - /home/algiz/volumes/mongo-shard12:/data/db
    ports:
      - 27011:27017
    networks:
      - mongo
    entrypoint: [ "/usr/bin/mongod", "--shardsvr", "--bind_ip_all", "--replSet", "shard1" ]

  shard2:
    image: mongo
    container_name: shard2
    restart: always
    volumes:
      - /home/algiz/volumes/mongo-shard2:/data/db
    ports:
      - 27020:27017
    networks:
      - mongo
    entrypoint: [ "/usr/bin/mongod", "--shardsvr", "--bind_ip_all", "--replSet", "shard2" ]

  shard22:
    image: mongo
    container_name: shard22
    restart: always
    volumes:
      - /home/algiz/volumes/mongo-shard22:/data/db
    ports:
      - 27021:27017
    networks:
      - mongo
    entrypoint: [ "/usr/bin/mongod", "--shardsvr", "--bind_ip_all", "--replSet", "shard2" ]

networks:
  mongo:
    driver: bridge